version: "3.9"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # init: crée le bucket 'scanned-docs' automatiquement quand MinIO est prêt
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minio minio12345 &&
      mc mb -p local/scanned-docs || true &&
      mc anonymous set none local/scanned-docs
      "
    restart: "no"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: myscandoc
      POSTGRES_USER: scan
      POSTGRES_PASSWORD: scanpwd
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scan -d myscandoc"]
      interval: 10s
      timeout: 5s
      retries: 5
